# ACES equivalent of HEMCO Example 5
species:
  co:
    - field: "MACCITY_CO"
      operation: "add"
  no:
    - field: "MACCITY_NO"
      operation: "add"
  so2:
    - field: "MACCITY_SO2"
      operation: "add"

cdeps_config:
  streams:
    - name: "MACCITY_CO"
      file_path: "data/MACCity_2000.nc"
    - name: "MACCITY_NO"
      file_path: "data/MACCity_2000.nc"
    - name: "MACCITY_SO2"
      file_path: "data/MACCity_2000.nc"
